### ISSUE TITLE
[BUG] App Runner cannot handle Windows Path properly

### ISSUE THREAD

**Issue by gigony** [Project-MONAI/monai-deploy-app-sdk#152]
(Thanks **thibault.pelletier** for reporting this issue!)

**Describe the bug**
We haven't tested the package in the Windows environment (Python on Windows for developing and Running it on Docker).
Building package is working but App runner cannot launch it properly.

```
Creating the docker image has worked fine but when trying to execute it I run into the following problem :
monai-deploy run simple_app:latest input output
Checking dependencies...
--> Verifying if "docker" is installed...

--> Verifying if "simple_app:latest" is available...

Checking for MAP "simple_app:latest" locally
"simple_app:latest" found.

Reading MONAI App Package manifest...
docker: Error response from daemon: mkdir C:UsersThibaultAppDataLocalTemptmpb8re0le4: Access is denied.
See 'docker run --help'.
ERROR: Failed to fetch MAP manifest.
Execution Aborted
```

After fixing the particular issue by the following code, there are still remaining issue to handle:
```diff
--- a/monai/deploy/runner/utils.py
+++ b/monai/deploy/runner/utils.py
@@ -41,8 +41,7 @@ def run_cmd(cmd: str) -> int:
     Returns:
         output: child process returncode after the command has been executed.
     """
-    args = shlex.split(cmd)
-    proc = subprocess.Popen(args, universal_newlines=True)
+    proc = subprocess.Popen(cmd, universal_newlines=True, shell=True)
     return proc.wait()
```

```bash
After upgrading the package, re packaging the app, and running from windows I get the following error : 

Traceback (most recent call last):
  File "/opt/monai/app/app.py", line 53, in <module>
    App(do_run=True)
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/core/application.py", line 129, in init
    self.run(log_level=args.log_level)
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/core/application.py", line 429, in run
    executor_obj.run()
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/core/executors/single_process_executor.py", line 125, in run
    op.compute(op_exec_context.input_context, op_exec_context.output_context, op_exec_context)
  File "/opt/monai/app/sobel_operator.py", line 34, in compute
    data_in = io.imread(input_path)[:, :, :3]  # discard alpha channel if exists
  File "/home/monai/.local/lib/python3.8/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, plugin_args)
  File "/home/monai/.local/lib/python3.8/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, kwargs)
  File "/home/monai/.local/lib/python3.8/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, kwargs))
  File "/opt/conda/lib/python3.8/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", kwargs)
  File "/opt/conda/lib/python3.8/site-packages/imageio/core/functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/imageio/core/request.py", line 124, in init
    self._parse_uri(uri)
  File "/opt/conda/lib/python3.8/site-packages/imageio/core/request.py", line 260, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/var/monai/\var\monai\input'
```

From https://discord.com/channels/854377741825998868/874812709210828830/891021849742417982

Even though we do not have a plan to support Windows (non-WSL) yet, it would be nice to handle the issue properly.

**Steps/Code to reproduce bug**

Both building image and launch the packaged app on Windows (non-WSL).

**Expected behavior**

Should work without error.

**Environment details (please complete the following information)**

- OS/Platform: Windows 10
- Python Version: 3.8
- Method of MONAI Deploy App SDK install: pip
- SDK Version: 0.1.0

**Comment by gigony** [comment]
I hope @Thibault-Pelletier is you(thibault.pelletier on Discord)

Trying to push PR to resolve this issue:
https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/153

Currently, the new package is in Test PyPI.
```bash
pip install -i https://test.pypi.org/simple/ monai-deploy-app-sdk==0.1.1rc2
```

Couldn't test on Windows yet (having trouble installing Docker Desktop for Windows).
Please help test it if you are available.
Or, I would resolve Docker installation issue and test on Windows.

**Comment by Thibault-Pelletier** [comment]
Hi @gigony,
Thank you for the update. 
I will try the new test version today or tomorrow and let you know how it goes on my end!

**Comment by Thibault-Pelletier** [comment]
Hi @gigony,
I just ran the simple_app from scratch on Windows with the new release candidate and now everything works perfectly!
Thanks!

**Comment by gigony** [comment]
Thank you @Thibault-Pelletier for the feedback!
