### ISSUE TITLE
Issue with simple image app tutorial (shell execution) [BUG] 

### ISSUE THREAD

**Issue by n-johe** [Project-MONAI/monai-deploy-app-sdk#500]
**Describe the bug**
When I run this line of code from the tutorial:
       monai-deploy run simple_app-x64-workstation-dgpu-linux-amd64:latest -i $HOLOSCAN_INPUT_PATH -o output
I get the following error:
       [INFO] Launching application python3 /opt/holoscan/app ...

Error processing line 1 of /home/holoscan/.local/lib/python3.10/site-packages/holoscan-2.2.0.post1.pth:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 192, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/holoscan/.local/lib/python3.10/site-packages/wheel_axle/runtime/__init__.py", line 80, in finalize
    with FileLock(lock_path):
  File "/home/holoscan/.local/lib/python3.10/site-packages/filelock/_api.py", line 376, in __enter__
    self.acquire()
  File "/home/holoscan/.local/lib/python3.10/site-packages/filelock/_api.py", line 332, in acquire
    self._acquire()
  File "/home/holoscan/.local/lib/python3.10/site-packages/filelock/_unix.py", line 42, in _acquire
    fd = os.open(self.lock_file, open_flags, self._context.mode)
PermissionError: [Errno 13] Permission denied: '/home/holoscan/.local/lib/python3.10/site-packages/holoscan-2.2.0.post1.dist-info/axle.lck'

**Steps/Code to reproduce bug**
Follow the tutorial for 'Create a simple image app' (shell execution) using the latest version.

**Expected behavior**
I expected an image to be produced without any errors stopping the execution.

**Environment details (please complete the following information)**

- OS/Platform: GCP compute engine Ubuntu 22.04 virtual machine
- Python Version: Python3.10
- Method of MONAI Deploy App SDK install: pip
- SDK Version: latest

**Additional context**
I tried to fix the issue by SSH'ing into the running container and changing permissions for this part of the error:

      PermissionError: [Errno 13] Permission denied: '/home/holoscan/.local/lib/python3.10/site-packages/holoscan-2.2.0.post1.dist-
     info/axle.lck' 

This didnt work.

**Comment by MMelQin** [comment]
@n-johe Thanks for reporting this. This issue with the underlying holoscan sdk Wheel axle.lck permission was also found in Holoscan SDK v2.3 when the app container is built with root user package install. One of the fixes is to use explicit --root-user-action when pip installing holoscan. Will update this bug with proper fix.
